DROP TABLE IF EXISTS user;
CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  password VARCHAR(64) NULL DEFAULT NULL COMMENT '密码',
  age INT(11) NULL DEFAULT NULL COMMENT '年龄',
  email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stock
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(30) NULL DEFAULT NULL COMMENT '编号',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '名称',
  type VARCHAR(30) NULL DEFAULT NULL COMMENT '类型',
  PRIMARY KEY (id)
);